index:
   path: /
   controller: App\Controller\TrickController::index

tricks:
   path: /tricks
   controller: App\Controller\TrickController::getAllTricks

display_trick:
   path: /tricks/{slug}
   controller: App\Controller\TrickController::getOneTrick

login:
   path: /login
   controller: App\Controller\AuthController::login

logout:
   path: /logout
   methods: GET