App\Entity\TrickGroup:
  type: entity
  table: trickGroup

  id:
    id:
      type: integer
      generator:
        strategy: AUTO

  fields:
    name:
      type: string
      length: 255
    tricks:
      type: array


  manyToOne:
    trickGroups:
      targetEntity: Add\Entity\TrickGroup