App\Entity\Trick:
  type: entity
  table: trick

  id:
    id:
      type: integer
      generator:
        strategy: AUTO

  fields:
    name:
      type: string
      length: 255
      unique: TRUE
    description:
      type: string
      length: 255
    slug:
      type: string
      length: 255
    coverImage:
      type: string
      length: 255
    image:
      type: string
      length: 255
    video:
      type: string
      length: 255

  manyToOne:
    user:
      targetEntity: App\Entity\User
      joinColumn:
        name: user_id
        referenceColumnName: id
