App\Entity\User:
  type: entity
  table: user

  id:
    id:
      type: integer
      generator:
        strategy: AUTO

  fields:
    firstname:
      type: string
      length: 255
    lastname:
      type: string
      length: 255
    username:
      type: string
      length: 255
      unique: true
    emailAddress:
      type: string
      length: 255
      unique: true
    password:
      type: string
      length: 255
    profileImage:
      type: string
      length: 255
    roles:
      type: array
